/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
<<<<<<< HEAD:.metadata/.plugins/org.eclipse.wst.server.core/tmp0/work/Catalina/localhost/Keisanchan/org/apache/jsp/home_jsp.java
 * Generated at: 2018-08-16 05:55:47 UTC
=======
 * Generated at: 2018-08-11 18:31:41 UTC
>>>>>>> 5aecbadb51d311424cf5379840e41bfb406e00a1:.metadata/.plugins/org.eclipse.wst.server.core/tmp0/work/Catalina/localhost/ecsite/org/apache/jsp/login_jsp.java
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
<<<<<<< HEAD:.metadata/.plugins/org.eclipse.wst.server.core/tmp0/work/Catalina/localhost/Keisanchan/org/apache/jsp/home_jsp.java
    _jspx_dependants.put("jar:file:/C:/Users/internousdev/Desktop/workspace/workspace-hattori/Keisanchan/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Keisanchan/WEB-INF/lib/struts2-core-2.3.32.jar!/META-INF/struts-tags.tld", Long.valueOf(1488769580000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.32.jar", Long.valueOf(1533542898671L));
=======
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.34.jar", Long.valueOf(1533967975650L));
    _jspx_dependants.put("jar:file:/C:/Users/maruk/Desktop/workspace/workspace-hattori/Keisanchan/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ecsite/WEB-INF/lib/struts2-core-2.3.34.jar!/META-INF/struts-tags.tld", Long.valueOf(1504613532000L));
>>>>>>> 5aecbadb51d311424cf5379840e41bfb406e00a1:.metadata/.plugins/org.eclipse.wst.server.core/tmp0/work/Catalina/localhost/ecsite/org/apache/jsp/login_jsp.java
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fform_0026_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005furl_0026_005faction_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fform_0026_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005furl_0026_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fform_0026_005faction.release();
    _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fs_005furl_0026_005faction_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta http-equiv=\"Content-Style-Type\" content=\"text/css\" />\r\n");
      out.write("<meta http-equiv=\"Content-Script-Type\" content=\"text/javascript\" />\r\n");
      out.write("<meta http-equiv=\"imagetoolbar\" content=\"no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("<title>Home画面</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("   body{\r\n");
      out.write("      margin:0;\r\n");
      out.write("      padding:0;\r\n");
      out.write("      line-height:1.6;\r\n");
      out.write("      letter-spacing:1px;\r\n");
      out.write("      font-family:Verdana, Helvetica, sans-serif;\r\n");
      out.write("      font-size:12px;\r\n");
      out.write("      color:#333;\r\n");
      out.write("      background:#fff;\r\n");
      out.write("   }\r\n");
      out.write("   table{\r\n");
      out.write("     text-align:center;\r\n");
      out.write("     margin:o auto;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   #top{\r\n");
      out.write("     width:780px;\r\n");
      out.write("     margin:30px auto;\r\n");
      out.write("     border:1px solid #333;\r\n");
      out.write("   }\r\n");
      out.write("   #header{\r\n");
      out.write("     width:100%;\r\n");
      out.write("     height:80px;\r\n");
      out.write("     background-color:black;\r\n");
      out.write("   }\r\n");
      out.write("   #main{\r\n");
      out.write("     width:100%;\r\n");
      out.write("     height:500px;\r\n");
      out.write("     text-align:center;\r\n");
      out.write("   }\r\n");
      out.write("   #footer{\r\n");
      out.write("     width:100%;\r\n");
      out.write("     height:80px;\r\n");
      out.write("     background-color:black;\r\n");
      out.write("     clear:both;\r\n");
      out.write("   }\r\n");
      out.write("   #text-center{\r\n");
      out.write("      display:inline-block;\r\n");
      out.write("      text-align:center;\r\n");
      out.write("   }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div id=\"header\">\r\n");
      out.write("         <div id=\"pr\">\r\n");
      out.write("         </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"main\">\r\n");
      out.write("         <div id=\"top\">\r\n");
      out.write("              <p>Home</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--               <form oninput=\"document.getElementByName('roe').value = -->\r\n");
      out.write("<!--  \t\t\t\t\tparseInt(document.getElementByName('toki').value, 10) / -->\r\n");
      out.write("<!--  \t\t\t\t\tparseInt(document.getElementByName('zikoshi').value, 10)\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t<p>当期純利益<input type=\"number\" name=\"toki\"><p/> -->\r\n");
      out.write("<!-- \t\t\t\t\t<br><p>自己資本<input type=\"number\" name=\"zikoshi\"></p> -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t<output for=\"toki zikoshi\" name=\"roe\">計算結果</output> -->\r\n");
      out.write("<!-- \t\t\t\t\t<output for=\"toki zikoshi\" name=\"roe\">計算結果</output> -->\r\n");
      out.write("<!-- \t\t\t\t\t<output for=\"toki zikoshi\" name=\"roe\">計算結果</output> -->\r\n");
      out.write("<!-- \t\t\t\t\t</form> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form>\r\n");
      out.write("        <label for=\"toki\">当期純利益 </label>\r\n");
      out.write("        <input type=\"text\" name=\"toki\"><br>\r\n");
      out.write("        <label for=\"zikoshi\">自己資本: </label>\r\n");
      out.write("        <input type=\"text\" name=\"zikoshi\">\r\n");
      out.write("\r\n");
      out.write("         <label for=\"keijo\">経常利益 </label>\r\n");
      out.write("        <input type=\"text\" name=\"keijo\"><br>\r\n");
      out.write("        <label for=\"uriage\">売上高: </label>\r\n");
      out.write("        <input type=\"text\" name=\"uriage\">\r\n");
      out.write("\r\n");
      out.write("        <br><button name=\"button\">計算する</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <label for=\"roe\">ROE: </label>\r\n");
      out.write("    <input type=\"text\" name=\"roe\"><br>\r\n");
      out.write("     <label for=\"uriage_keijo_ratio\">売上高経常利益率: </label>\r\n");
      out.write("    <input type=\"text\" name=\"uriage_keijo_ratio\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("// ボタンの要素を取得\r\n");
      out.write("  var button = document.getElementByName(\"button\");\r\n");
      out.write("\r\n");
      out.write(" // ボタンをクリックした時の処理\r\n");
      out.write("  button.addEventListener(\"click\", function(e) {\r\n");
      out.write("\r\n");
      out.write("     e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("     // 2つの入力フォームの値を取得\r\n");
      out.write("     var toki = document.getElementByName(\"toki\").value;\r\n");
      out.write("     var zikoshi = document.getElementByName(\"zikoshi\").value;\r\n");
      out.write("     var keijo = document.getElementByName(\"keijo\").value;\r\n");
      out.write("     var uriage = document.getElementByName(\"uriage\").value;\r\n");
      out.write("\r\n");
      out.write("     // 2つの数値を足す -->\r\n");
      out.write("     var sum = parseInt(toki, 10) + parseInt(zikoshi, 10);\r\n");
      out.write("     var sum = parseInt(uriage, 10) / parseInt(keijo, 10);\r\n");
      out.write("\r\n");
      out.write("     // 足し算の結果を別の入力フォームに表示\r\n");
      out.write("     var roe = document.getElementByName(\"roe\");\r\n");
      out.write("     roe.value = sum;\r\n");
      out.write("\r\n");
      out.write("      var uriage_keijo_ratio = document.getElementByName(\"uriage_keijo_ratio\");\r\n");
      out.write("      uriage_keijo_ratio.value = sum;\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t <form =\"KeisanAction\"> -->\r\n");
      out.write("\r\n");
      out.write("<!-- <form> -->\r\n");
      out.write("<!-- <p>当期純利益<input type=\"number\" name=\"toki\" value=\"\"><p/> -->\r\n");
      out.write("<!-- <br><p>自己資本<input type=\"number\" name=\"zikoshi\" value=\"\"></p> -->\r\n");
      out.write("<!-- <br><p>経常利益<input type=\"number\" name=\"keijo\" value=\"\"></p> -->\r\n");
      out.write("<!-- <br><p>売上高<input type=\"number\" name=\"uriage\" value=\"\"></p> -->\r\n");
      out.write("<!-- <br><p>売上総利益<input type=\"number\" name=\"uriage_sori\" value=\"\"></p> -->\r\n");
      out.write("<!-- <br><p>営業利益<input type=\"number\" name=\"eigyo\" value=\"\"></p> -->\r\n");
      out.write("<!-- <br><p>総資産<input type=\"number\" name=\"total_assets\" value=\"\"></p> -->\r\n");
      out.write("<!-- <br><p>売上債権<input type=\"number\" name=\"uriage_saiken\" value=\"\"></p> -->\r\n");
      out.write("<!-- <br><p>売上原価<input type=\"number\" name=\"uriage_genka\" value=\"\"></p> -->\r\n");
      out.write("<!-- <br><p>棚卸資産<input type=\"number\" name=\"tana\" value=\"\"></p> -->\r\n");
      out.write("<!-- <br><p>流動資産<input type=\"number\" name=\"ryudo_assets\" value=\"\"></p> -->\r\n");
      out.write("<!-- <br><p>流動負債<input type=\"number\" name=\"ryudo_fusai\" value=\"\"></p> -->\r\n");
      out.write("<!-- <br><p>固定資産<input type=\"number\" name=\"kotei_assets\" value=\"\"></p> -->\r\n");
      out.write("<!-- <br><p>負債合計<input type=\"number\" name=\"total_fusai\" value=\"\"></p> -->\r\n");
      out.write("\r\n");
      out.write("<!-- <label for=\"roe\">ROE: </label> -->\r\n");
      out.write("<!--  <input type=\"text\" id=\"roe\"> -->\r\n");
      out.write("<!-- </form> -->\r\n");
      out.write("\r\n");
      out.write("// ver roe = toki/zikoshi;\r\n");
      out.write("// document.write(roe);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- </form> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("         <div id=\"text-center\">\r\n");
      out.write("              ");
      if (_jspx_meth_s_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("              ");
      if (_jspx_meth_s_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("         <div id = \"pr\">\r\n");
      out.write("         </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:form
    org.apache.struts2.views.jsp.ui.FormTag _jspx_th_s_005fform_005f0 = (org.apache.struts2.views.jsp.ui.FormTag) _005fjspx_005ftagPool_005fs_005fform_0026_005faction.get(org.apache.struts2.views.jsp.ui.FormTag.class);
    _jspx_th_s_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fform_005f0.setParent(null);
    // /home.jsp(171,14) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setAction("HomeAction");
    int _jspx_eval_s_005fform_005f0 = _jspx_th_s_005fform_005f0.doStartTag();
    if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fform_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fform_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("                      ");
        if (_jspx_meth_s_005fsubmit_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("              ");
        int evalDoAfterBody = _jspx_th_s_005fform_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fform_0026_005faction.reuse(_jspx_th_s_005fform_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fform_0026_005faction.reuse(_jspx_th_s_005fform_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fsubmit_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:submit
    org.apache.struts2.views.jsp.ui.SubmitTag _jspx_th_s_005fsubmit_005f0 = (org.apache.struts2.views.jsp.ui.SubmitTag) _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.ui.SubmitTag.class);
    _jspx_th_s_005fsubmit_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fsubmit_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /home.jsp(172,22) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fsubmit_005f0.setValue("計算する？");
    int _jspx_eval_s_005fsubmit_005f0 = _jspx_th_s_005fsubmit_005f0.doStartTag();
    if (_jspx_th_s_005fsubmit_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fsubmit_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fsubmit_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fsubmit_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f0 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    _jspx_th_s_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fif_005f0.setParent(null);
    // /home.jsp(174,14) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fif_005f0.setTest("#session.id !=null");
    int _jspx_eval_s_005fif_005f0 = _jspx_th_s_005fif_005f0.doStartTag();
    if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fif_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fif_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("                      <p>ログアウトする場合は<a href='");
        if (_jspx_meth_s_005furl_005f0(_jspx_th_s_005fif_005f0, _jspx_page_context))
          return true;
        out.write("'>こちら</a></p>\r\n");
        out.write("              ");
        int evalDoAfterBody = _jspx_th_s_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f0 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005faction_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f0);
    // /home.jsp(175,44) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f0.setAction("LoginAction");
    int _jspx_eval_s_005furl_005f0 = _jspx_th_s_005furl_005f0.doStartTag();
    if (_jspx_th_s_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f0);
    return false;
  }
}
